### ISSUE TITLE
Panic parsing test with binary image

### ISSUE THREAD

**Issue by szferi** [namespacelabs/foundation#1042]
Attached is an example that can help to reproduce the issue. 
The main problem that if the test has `imageFrom: binary: "something` and that binary is not defined in the given package then I got the following panic:

```
panic: runtime error: index out of range [-1] [recovered]
        panic: (tasks.handledPanic) 0x14000898890 [recovered]
        panic: (tasks.handledPanic) 0x14000898890

goroutine 91 [running]:
namespacelabs.dev/foundation/std/tasks.panicHandler({0x1400044c6f0?, 0x0?})
        /Users/szferi/Projects/ns/ns-foundation/std/tasks/actions.go:274 +0x48
panic({0x1071c64e0, 0x14000898890})
        /opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/panic.go:884 +0x204
namespacelabs.dev/foundation/std/tasks.panicHandler({0x1400044c6f0?, 0x0?})
        /Users/szferi/Projects/ns/ns-foundation/std/tasks/actions.go:278 +0x70
panic({0x1074017e0, 0x14000533518})
        /opt/homebrew/Cellar/go/1.19.4/libexec/src/runtime/panic.go:884 +0x204
namespacelabs.dev/foundation/internal/frontend/cuefrontend.parseTest({0x10762f568, 0x14000a35f50}, 0x14000890d30?, {0x1076312f0, 0x140008c3200}, 0x14000a71d40, {0x14000a332b0, 0x8}, 0x140008e86c0)
        /Users/szferi/Projects/ns/ns-foundation/internal/frontend/cuefrontend/tests.go:84 +0x5a4
namespacelabs.dev/foundation/internal/frontend/cuefrontend.parseTests({0x10762f568, 0x14000a35f50}, 0x14000a43830?, {0x1076312f0, 0x140008c3200}, 0x104f0e2c4?, 0x14000b46750?)
        /Users/szferi/Projects/ns/ns-foundation/internal/frontend/cuefrontend/tests.go:42 +0x130
namespacelabs.dev/foundation/internal/frontend/cuefrontend.ParsePackage({0x10762f568, 0x14000a35f50}, 0x19?, {0x1076312f0, 0x140008c3200}, 0x1066bedd9?, {0x14000642ba0, {0x1400015e920, 0x19}, {0x1400015e8d3, ...}})
        /Users/szferi/Projects/ns/ns-foundation/internal/frontend/cuefrontend/package.go:24 +0xfc
namespacelabs.dev/foundation/internal/frontend/cuefrontendopaque.Frontend.ParsePackage({{0x1076312f0?, 0x140008c3200?}, 0x14000a9e3f0?}, {0x10762f568?, 0x14000a35f50}, 0x14000a766c0, {0x14000642ba0, {0x1400015e920, 0x19}, {0x1400015e8d3, ...}})
        /Users/szferi/Projects/ns/ns-foundation/internal/frontend/cuefrontendopaque/phase0.go:60 +0x224
namespacelabs.dev/foundation/internal/frontend/cuefrontend.impl.ParsePackage({{0x1076312f0, 0x140008c3200}, 0x14000a9e3f0, 0x14000a35980, {0x1075fcd60, 0x14000a58048}}, {0x10762f568, 0x14000a35f50}, {0x14000642ba0, {0x1400015e920, ...}, ...})
        /Users/szferi/Projects/ns/ns-foundation/internal/frontend/cuefrontend/frontend.go:93 +0x874
namespacelabs.dev/foundation/internal/parsing.(*loadingPackage).Ensure.func1({0x10762f568, 0x14000a35f50})
        /Users/szferi/Projects/ns/ns-foundation/internal/parsing/loader.go:359 +0x7c
namespacelabs.dev/foundation/std/tasks.Return[...].func1()
        /Users/szferi/Projects/ns/ns-foundation/std/tasks/actions.go:347 +0x34
namespacelabs.dev/foundation/std/tasks.(*RunningAction).Call(0x14000a64000, {0x10762f568, 0x14000a35c50}, 0x140008e9128)
        /Users/szferi/Projects/ns/ns-foundation/std/tasks/actions.go:659 +0xa8
namespacelabs.dev/foundation/std/tasks.(*ActionEvent).RunWithOpts(0x140008e9230, {0x10762f568, 0x14000a35c50}, {0x0?, 0x140008e9128?})
        /Users/szferi/Projects/ns/ns-foundation/std/tasks/actions.go:330 +0x510
namespacelabs.dev/foundation/std/tasks.Return[...]({0x10762f568?, 0x14000a35c50?}, 0x19?, 0x14000642ba0?)
        /Users/szferi/Projects/ns/ns-foundation/std/tasks/actions.go:345 +0x58
namespacelabs.dev/foundation/internal/parsing.(*loadingPackage).Ensure(0x140008c3280, {0x10762f568, 0x14000a35c50})
        /Users/szferi/Projects/ns/ns-foundation/internal/parsing/loader.go:358 +0x2ac
namespacelabs.dev/foundation/internal/parsing.(*PackageLoader).ensurePackage(0x140008c3200, {0x10762f568, 0x14000a35c50}, {0x1400015e8c0, 0x19})
        /Users/szferi/Projects/ns/ns-foundation/internal/parsing/loader.go:256 +0x184
namespacelabs.dev/foundation/internal/parsing.(*PackageLoader).LoadByName(0x140008c3200, {0x10762f568, 0x14000a35c50}, {0x1400015e8c0, 0x19})
        /Users/szferi/Projects/ns/ns-foundation/internal/parsing/loader.go:225 +0x130
namespacelabs.dev/foundation/internal/cli/fncobra.(*ServersParser).Parse.func1({0x10762f568, 0x14000a35c50})
        /Users/szferi/Projects/ns/ns-foundation/internal/cli/fncobra/serverbound.go:55 +0x10c
namespacelabs.dev/foundation/std/tasks.(*RunningAction).Call(0x140002d1e40, {0x10762f4c0, 0x140004348c0}, 0x140008e9c00)
        /Users/szferi/Projects/ns/ns-foundation/std/tasks/actions.go:659 +0xa8
namespacelabs.dev/foundation/std/tasks.(*ActionEvent).RunWithOpts(0x14000b28a00, {0x10762f4c0, 0x140004348c0}, {0x0?, 0x140008e9c00?})
        /Users/szferi/Projects/ns/ns-foundation/std/tasks/actions.go:330 +0x510
namespacelabs.dev/foundation/std/tasks.(*ActionEvent).Run(...)
        /Users/szferi/Projects/ns/ns-foundation/std/tasks/actions.go:334
namespacelabs.dev/foundation/internal/cli/fncobra.(*ServersParser).Parse(0x140002ca0c0?, {0x10762f4c0?, 0x140004348c0?}, {0x14000838eb0?, 0x0?, 0x0?})
        /Users/szferi/Projects/ns/ns-foundation/internal/cli/fncobra/serverbound.go:54 +0x474
namespacelabs.dev/foundation/internal/cli/fncobra.(*CommandCtrl).DoWithArgs.func1({0x10762f4c0, 0x140004348c0}, {0x14000838eb0, 0x1, 0x1})
        /Users/szferi/Projects/ns/ns-foundation/internal/cli/fncobra/do.go:122 +0xd8
namespacelabs.dev/foundation/internal/cli/fncobra.RunE.func1(0x1400093ca00?, {0x14000838eb0?, 0x1?, 0x1?})
        /Users/szferi/Projects/ns/ns-foundation/internal/cli/fncobra/do.go:29 +0x44
github.com/spf13/cobra.(*Command).execute(0x1400093ca00, {0x140001241a0, 0x1, 0x1})
        /Users/szferi/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x140003d0f00)
        /Users/szferi/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/szferi/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/szferi/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
namespacelabs.dev/foundation/internal/cli/fncobra.DoMain.func2({0x10762f4c0?, 0x140004348c0?})
        /Users/szferi/Projects/ns/ns-foundation/internal/cli/fncobra/main.go:409 +0x58
namespacelabs.dev/foundation/internal/cli/fncobra.RunInContext.func1({0x10762f4c0?, 0x140004348c0?})
        /Users/szferi/Projects/ns/ns-foundation/internal/cli/fncobra/do.go:77 +0x8c
namespacelabs.dev/foundation/internal/executor.(*Executor).Go.func1()
        /Users/szferi/Projects/ns/ns-foundation/internal/executor/errgroup.go:70 +0x30
namespacelabs.dev/foundation/internal/executor.(*Executor).lowlevelGo.func1()
        /Users/szferi/Projects/ns/ns-foundation/internal/executor/errgroup.go:59 +0x60
created by namespacelabs.dev/foundation/internal/executor.(*Executor).lowlevelGo
        /Users/szferi/Projects/ns/ns-foundation/internal/executor/errgroup.go:56 +0x8c
``` 

[ns-test.zip](https://github.com/namespacelabs/foundation/files/10372817/ns-test.zip)

**Comment by n-g** [comment]
Thanks for reporting!

c700c11908b0db3e927ff9353244b79407864833 fixes this.
